feature: multistage dockerfile for nginx with nap and agent
nginxinc/docker-nginx-controller pull request #23
Opened 2020-11-30 15:44 UTC by luk90

part of ind-19134

NAP setup for ubuntu

2020-12-02 08:22 UTC, azych approved these changes

2020-12-04 15:17 UTC, apasyniuk requested changes

2020-12-04 15:17 UTC, apasyniuk commented on centos/nap/entrypoint.sh
> +/bin/su -s /bin/bash -c '/opt/app_protect/bin/bd_agent &' nginx
You just run this in the background and do not handle any kind of graceful shutdown. Do that as in the case of agent or Nginx(same in all entrypoint versions)

2020-12-04 15:17 UTC, apasyniuk commented on debian/nap/entrypoint.sh
> +if [ -n "${api_key}" -o -n "${instance_name}" -o -n "${controller_url}" -o -n "${location}" ]; then
Check for `controller_url` is not needed here I think.

2020-12-04 15:17 UTC, apasyniuk commented on debian/nap/nginx-plus-api.conf
> +    app_protect_security_log "/etc/nginx/custom_log_format.json" stderr;
Indent.

2020-12-07 19:39 UTC, apasyniuk approved these changes

2020-12-07 20:52 UTC, 1996sajal commented
Tests are failing on NAP docker containers when WAF_ENABLED.
`RuntimeError: The component entered an isError state while checking for configuration.See data provided in currentStatus.state.conditions: [{'message': 'The Security module could not be found on the following NGINX instances: i-0041bbb0960bae1b6', 'type': 'config'}]`

2020-12-07 20:53 UTC, 1996sajal requested changes
Tests are failing on NAP docker containers when WAF_ENABLED.
`RuntimeError: The component entered an isError state while checking for configuration.See data provided in currentStatus.state.conditions: [{'message': 'The Security module could not be found on the following NGINX instances: i-0041bbb0960bae1b6', 'type': 'config'}]`

2020-12-08 08:37 UTC, 1996sajal approved these changes
There have to be certain changes made to Systest common the way NAP tests are run and I think the MR can be merged to master as of now.

2020-12-08 14:00 UTC, merged