Add ENV_CONTROLLER_API_URL for run-time controller configuration
nginxinc/docker-nginx-controller pull request #33
Opened 2020-12-15 16:43 UTC by apasyniuk

Add new parameter for run-time configuration of controller agent API URL.

2020-12-16 22:56 UTC, brianehlert commented on amazon/no-nap/entrypoint.sh
> +# If several instances use the same image name, the metrics will
image name is no longer a thing.  That was legacy from amplify

2020-12-16 22:57 UTC, brianehlert commented on centos/no-nap/entrypoint.sh
> +# If several instances use the same image name, the metrics will
imagename is legacy - this is not a thing any longer

2020-12-16 22:58 UTC, brianehlert commented on debian/no-nap/entrypoint.sh
> +# If several instances use the same image name, the metrics will
imagename again

2020-12-16 22:59 UTC, brianehlert requested changes
imagename and imagename behavior is no longer a thing.  References should be removed.

2020-12-17 10:06 UTC, azych approved these changes

2020-12-17 19:12 UTC, brianehlert approved these changes

2020-12-18 12:20 UTC, merged