feature: parametrizing nplus version in nap enabled examples
nginxinc/docker-nginx-controller pull request #37
Opened 2020-12-31 13:06 UTC by luk90

Installing specific version of NAP depending on `NGINX_PLUS_VERSION` parameter.
Feature works in Debian and Centos examples.
For Ubuntu, always newest N+ and NAP are installed.

2021-01-04 09:58 UTC, apasyniuk requested changes

2021-01-04 09:58 UTC, apasyniuk commented on centos/nap/Dockerfile
> +RUN if [ "$NGINX_PLUS_VERSION" -lt 23 ] ; \
When user specifies not supported nginx plus release version by nap then make it as hard error.

2021-01-04 10:05 UTC, apasyniuk commented
Add to README.md information about the supported version of nap for specific os,
and for nap ubuntu add hard error that only 23 version is supported.

2021-01-04 16:53 UTC, 1996sajal approved these changes

2021-01-08 16:38 UTC, brianehlert approved these changes

2021-01-11 09:08 UTC, apasyniuk approved these changes

2021-01-11 09:39 UTC, merged