refactor: renamed and changed format of CTRL_HOST variable for agent …
nginxinc/docker-nginx-controller pull request #39
Opened 2021-01-08 15:07 UTC by luk90

…layer examples

2021-01-08 15:20 UTC, 1996sajal approved these changes
I guess it was missed. Thanks.

2021-01-11 10:03 UTC, apasyniuk requested changes

2021-01-11 10:03 UTC, apasyniuk commented on debian/examples/agent-layer/Dockerfile
>  # Example solution for multiple service management in docker image could be found in official docker
Change comment with example in lines 4 and 5 of this file.

2021-01-11 10:03 UTC, apasyniuk commented on ubuntu/examples/agent-layer/Dockerfile
>  # Example solution for multiple service management in docker image could be found in official docker
Change comment with example in lines 4 and 5 of this file.

2021-01-12 11:47 UTC, merged